version: '3.8'

services:
    postgres:
        image: postgres:15
        container_name: zaptask_postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: zaptask_db
            POSTGRES_USER: zaptask_user
            POSTGRES_PASSWORD: zaptask_pass
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
